/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daftarAnime;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Adin
 */
public class studioForm extends javax.swing.JFrame {

    String filename = null;
    String path2 = null;
    dbConnection db;
    boolean stat = true;
    int id;
    
    /**
     * Creates new form studioForm
     */
    public studioForm() {
        initComponents();
        db = new dbConnection();
        
    }
    
     public studioForm(String status, boolean stat, int id) {
        initComponents();
        db = new dbConnection();
        statusLbl.setText(status);
        this.stat = stat;
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTx = new javax.swing.JTextField();
        tahunTx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uploadB = new javax.swing.JButton();
        submitB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        statusLbl.setText("ADD STUDIO");

        jLabel2.setText("Name:");

        jLabel3.setText("Tahun didirikan:");

        tahunTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunTxActionPerformed(evt);
            }
        });

        jLabel4.setText("Image:");

        uploadB.setText("Upload");
        uploadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBActionPerformed(evt);
            }
        });

        submitB.setText("Submit");
        submitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(statusLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTx, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tahunTx, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uploadB))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(statusLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tahunTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uploadB))
                .addGap(36, 36, 36)
                .addComponent(submitB)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tahunTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunTxActionPerformed

    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        // TODO add your handling code here:
        String name = nameTx.getText();
        String tahun = tahunTx.getText();
        int id = this.id;
        Connection s = (Connection) db.getConn();
        String sqlquery;
        sqlquery = "INSERT INTO studio (name, tahun, image) VALUES ( ?, ?, ?)";
        
        if(stat==true){
            try{
                PreparedStatement pst = (PreparedStatement) s.prepareStatement(sqlquery);
                pst.setString(1, name);
                pst.setString(2, tahun);
                InputStream is = new FileInputStream(new File(path2));
                pst.setBlob(3, is);
                pst.execute();
                nameTx.setText("");
                tahunTx.setText("");
                JOptionPane.showMessageDialog(null,"Data berhasil ditambahkan!");
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        } else {
            sqlquery = "UPDATE studio SET name = ?, tahun = ?, image = ? WHERE id = ?";
            try{
                PreparedStatement pst = (PreparedStatement) s.prepareStatement(sqlquery);
                pst.setString(1, name);
                pst.setString(2, tahun);
                InputStream is = new FileInputStream(new File(path2));
                pst.setBlob(3, is);
                pst.setInt(4, id);
                pst.execute();
                nameTx.setText("");
                tahunTx.setText("");
                JOptionPane.showMessageDialog(null,"Data berhasil dirubah");
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
//
        
    }//GEN-LAST:event_submitBActionPerformed

    private void uploadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(filename));
            Image img = bi.getScaledInstance(110, 142, SCALE_SMOOTH);
            path2 = filename;
            
        } catch (IOException ex) {
            Logger.getLogger(animeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uploadBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTx;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JButton submitB;
    private javax.swing.JTextField tahunTx;
    private javax.swing.JButton uploadB;
    // End of variables declaration//GEN-END:variables
}
